### ISSUE TITLE
I cannot install

### ISSUE THREAD

**Issue by kaiher** [alekseyenko/WdStar#7]
I tried to install WdStar with devtools::install_github( ), but failed owing to a HTTP error 404. How can I install this package?

Kind regards,

FYI, I show the log, below.
install_github("alekseyenko/WdStar")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`alekseyenko`) and repo name (`WdStar`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by alekseyenko** [comment]
WdStart is not built as an R package yet. To use the methods you can just source directly from gihub, e.g.
source('https://raw.githubusercontent.com/alekseyenko/WdStar/master/Wd.R')

**Comment by kaiher** [comment]
OK. I can manage with following the way you answered!
I appreciate your help and that you make the cool software.
Kind regards,
